function [dipole] = calculate_CSD_dipole(data,high_channels,low_channels, window)
%{
Calculate the dipole of a 3D stack of ripple CSDs by calculating the max
and min of a CSD with specified high and low channels. 

Args:
    CSD (3D matrix): Matrix of CSD values, axis 1) data points, 2)
    channels, 3) ripples
    high_channels (1xn array): Array of which channels to include when
    calculating high CSD values
    low_channels (1xn array): Array of which channels to include when
    calculating low CSD values

Returns:
    dipole (1xn): array of max-min values, where n is the number of ripples
%}

high_values = squeeze(...
    mean(...
        mean(data(window,high_channels,:),...
            1),...
        2)...
    );

low_values = squeeze(...
    mean(...
        mean(data(window,low_channels,:),...
            1),...
        2)...
    );

dipole = high_values - low_values;
end